version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000" # Порт PHP-FPM
      - "6002:6002"  # Порт вебсокета
#    image: laravelapp
    container_name: quantum
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
 #     - ./docker/supervisor/conf.d/:/etc/supervisor/conf.d/
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: quantum
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - laravel

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: postgres
    container_name: quantum

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
